AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.LambdaMethodHandler::handleRequest
      Runtime: java8
      CodeUri: s3://electrolink-lambda-deployment-artifacts-123456789012/code/
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET